-- ===============================================================================
--   FCC CDBS Database
--   DESCRIPTION:       This is schema is for loading MYSQL publicly released files under CDBS.
--   URL:               http://transition.fcc.gov/ftp/Bureaus/MB/Databases/cdbs/_readme.html
--   DATA URL:          http://transition.fcc.gov/mb/databases/cdbs/
--   DOCUMENTATION:     http://transition.fcc.gov/mb/databases/cdbs/
--                      ftp://ftp.fcc.gov/pub/Bureaus/MB/Databases/cdbs/_Engineering_Data_Description.pdf
--   
-- ================================================================================

-- ================================================================================
--   mysql Load Script File
-- ================================================================================

-- ===============================================================================
-- 
--   Generated by:      Greg Elin
--                      See https://github.com/gregelin/FCC-CDBS 
-- 
--   Target Database:   mysql
--   Generated at:      November 24, 2011
--   File name:         fcc_cdbs_load_mysql.sql
--   Notes:             Not tested yet
-- 
-- ================================================================================

-- ================================================================================
--
--   IMPORTANT!!
--   MODIFY:            PATH TO DOWNLOADED DATA FILES
--
-- ================================================================================

-- SQL Load statements
-- Assumes tables are empty
-- --------------------------------------------------------------------

-- load am_ant_sys
LOAD DATA LOCAL INFILE '/codedata/FCC/data/public/cdbs/am_ant_sys.dat'
INTO TABLE am_ant_sys
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '^|\r'
(ant_mode, ant_sys_id, application_id, aug_count, bad_data_switch, domestic_pattern, dummy_data_switch, efficiency_restricted, efficiency_theoretical, feed_circ_other, feed_circ_type, hours_operation, lat_deg, lat_dir, lat_min, lat_sec, lon_deg, lon_dir, lon_min, lon_sec, q_factor, q_factor_custom_ind, power, rms_augmented, rms_standard, rms_theoretical, tower_count, eng_record_type, biased_lat, biased_long, mainkey, am_dom_status, lat_whole_secs, lon_whole_secs, ant_dir_ind, grandfathered_ind, specified_hrs_range, augmented_ind, @last_update_date)
set
last_update_date = str_to_date(@last_update_date, '%m/%d/%Y');

-- test> select application_id, last_update_date from am_ant_sys limit 5;



-- load am_towers.dat
LOAD DATA LOCAL INFILE '/codedata/FCC/data/public/cdbs/am_towers.dat'
INTO TABLE am_towers
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '^|\r'
(ant_sys_id, asrn_id, elec_hgt_deg, field_ratio, hag_no_obst, hgt_overall_mtr, hgt_rad_ab, hgt_radiator_mtr, orientation_deg, phasing_deg, rad_hgt_deg, spacing_deg, top_loaded_switch, topload_a, topload_b, topload_c, topload_d, tower_num, tower_pl_codes, tower_ref_switch, asrn_na_ind, topload_apparent_hgt, faa_notified_ind, tower_type, @last_update_date)
set
last_update_date = str_to_date(@last_update_date, '%m/%d/%Y');

-- Todo: adjust last_update_date, other fields for for null values
-- test> select asrn_id, last_update_date from am_towers limit 12;


-- End SQL